codecov:
  require_ci_to_pass: true
  max_report_age: 24

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error
        
    patch:
      default:
        target: 80%
        threshold: 10%
        base: auto
        
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/public/**"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/prisma/**"
