#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npx lint-staged

# Run type checking
npm run type-check

# Run tests for changed files
npm test -- --bail --findRelatedTests --passWithNoTests
